# Change these first
owner: Boof-Development # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Kukfest
    url: https://kukfest.eu
  - name: Kukfest merch
    url: https://merch.kukfest.eu
  - name: DB
    url: https://db.080609.xyz/_/
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.kukfest.eu
  # baseUrl: /your-repo-name
  logoUrl: https://kukfest.eu/img/favicon.png
  name: Upptime
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
